title: Sentiment Analysis
description: >-
  This will return a CSV of the sentiment analysis run on
  each sentence of the input documents.

  [Learn more about HuggingFace](https://huggingface.co/) and
  [HappyTransformer](https://happytransformer.com/)
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
  # By the current search query
  - querybv
# Properties can just be blank if you do not need any input data
properties: {}
categories:
  - ai
